# Generated by Django 5.2.1 on 2025-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('C++', 'cpp'), ('Java', 'java'), ('c', 'C')], max_length=10),
        ),
    ]
