# Generated by Django 5.2.1 on 2025-05-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_alter_codesubmission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('Python', 'python'), ('C++', 'cpp'), ('Java', 'java'), ('c', 'C')], max_length=10),
        ),
    ]
