# Generated by Django 5.2.1 on 2025-06-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_alter_codesubmission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('Python', 'python'), ('C++', 'cpp'), ('java', 'Java'), ('c', 'C')], max_length=10),
        ),
    ]
