# Generated by Django 5.2.1 on 2025-06-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0009_alter_codesubmission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('C++', 'cpp'), ('Java', 'java'), ('c', 'C')], max_length=10),
        ),
    ]
